# Project: Project6
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = diff.o
LINKOBJ  = diff.o
LIBS     = -L"X:/DEV-C++/Dev-Cpp/MinGW64/lib" -L"X:/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"X:/DEV-C++/Dev-Cpp/MinGW64/include" -I"X:/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"X:/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"X:/DEV-C++/Dev-Cpp/MinGW64/include" -I"X:/DEV-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"X:/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"X:/DEV-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = diff.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

diff.o: diff.cpp
	$(CPP) -c diff.cpp -o diff.o $(CXXFLAGS)
